version: '3.5'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: booking-api
    image: booking-api:1.0.0
    restart: always
    ports:
      - '3033:3033'
    environment:
      - PORT=3033
    depends_on:
      - mongo
    volumes:
      - /usr/src/app/node_modules
      - ./api:/usr/src/app/
      - ./api/uploads:/usr/src/app/uploads
    # networks:
    #   - booking-app

  mongo:
    image: mongo:4.4.4
    container_name: booking-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5
    # networks:
    #   - booking-app
# networks:
#   booking-app:
#     driver: bridge
